//
//  RTAbridged_cast.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "name" : "Tobey Maguire",
  "id" : "162660340",
  "characters" : [ "Spider-Man/Peter Parker" ]
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface RTAbridged_cast : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSArray *characters;


@property (nonatomic, copy) NSString *magnetId;


@property (nonatomic, copy) NSString *name;



@end
