//
//  RTAlternate_ids.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "imdb" : "2103281"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface RTAlternate_ids : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *imdb;



@end
