//
//  RTBoxOfficeResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "movies" : [ {
    "id" : "771357000",
    "posters" : {
      "original" : "http://content8.flixster.com/movie/11/18/08/11180834_tmb.jpg",
      "detailed" : "http://content8.flixster.com/movie/11/18/08/11180834_tmb.jpg",
      "thumbnail" : "http://content8.flixster.com/movie/11/18/08/11180834_tmb.jpg",
      "profile" : "http://content8.flixster.com/movie/11/18/08/11180834_tmb.jpg"
    },
    "synopsis" : "From director Clint Eastwood comes \"American Sniper,\" starring Bradley Cooper as Chris Kyle, the most lethal sniper in U.S. military history. But there was much more to this true American hero than his skill with a rifle. U.S. Navy SEAL sniper Chris Kyle is sent to Iraq with only one mission: to protect his brothers-in-arms. His pinpoint accuracy saves countless lives on the battlefield and, as stories of his courageous exploits spread, he earns the nickname \"Legend.\" However, his reputation is also growing behind enemy lines, putting a price on his head and making him a prime target of insurgents. Despite the danger, as well as the toll on his family at home, Chris serves through four harrowing tours of duty in Iraq, becoming emblematic of the SEAL creed to \"leave no man behind.\" But upon returning home, Chris finds that it is the war he can't leave behind. (C) Warner Bros",
    "abridged_cast" : [ {
      "name" : "Bradley Cooper",
      "id" : "351525448",
      "characters" : [ "Chris Kyle" ]
    }, {
      "name" : "Sienna Miller",
      "id" : "335716430",
      "characters" : [ "Taya" ]
    }, {
      "name" : "Luke Grimes",
        ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class RTLinks;

@interface RTBoxOfficeResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *link_template;


@property (nonatomic, strong) RTLinks *links;


@property (nonatomic, copy) NSArray *movies;



@end
