//
//  RTMovie.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "id" : "771308675",
  "posters" : {
    "original" : "http://content8.flixster.com/movie/11/18/91/11189194_tmb.jpg",
    "detailed" : "http://content8.flixster.com/movie/11/18/91/11189194_tmb.jpg",
    "thumbnail" : "http://content8.flixster.com/movie/11/18/91/11189194_tmb.jpg",
    "profile" : "http://content8.flixster.com/movie/11/18/91/11189194_tmb.jpg"
  },
  "synopsis" : "A growing nation of genetically evolved apes led by Caesar is threatened by a band of human survivors of the devastating virus unleashed a decade earlier. They reach a fragile peace, but it proves short-lived, as both sides are brought to the brink of a war that will determine who will emerge as Earth's dominant species. (c) Fox",
  "abridged_cast" : [ {
    "name" : "Andy Serkis",
    "id" : "269710329",
    "characters" : [ "Caesar" ]
  }, {
    "name" : "Jason Clarke",
    "id" : "359854726",
    "characters" : [ "Malcolm" ]
  }, {
    "name" : "Gary Oldman",
    "id" : "162652649",
        ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class RTAlternate_ids;
@class RTLinks;
@class RTPosters;
@class RTRatings;
@class RTRelease_dates;

@interface RTMovie : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSArray *abridged_cast;


@property (nonatomic, strong) RTAlternate_ids *alternate_ids;


@property (nonatomic, copy) NSString *critics_consensus;


@property (nonatomic, strong) RTLinks *links;


@property (nonatomic, copy) NSString *magnetId;


@property (nonatomic, copy) NSString *mpaa_rating;


@property (nonatomic, strong) RTPosters *posters;


@property (nonatomic, strong) RTRatings *ratings;


@property (nonatomic, strong) RTRelease_dates *release_dates;


@property (nonatomic, assign) int runtime;


@property (nonatomic, copy) NSString *synopsis;


@property (nonatomic, copy) NSString *title;


@property (nonatomic, assign) int year;



@end
