//
//  RTMovie.m
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
#import "RTMovie.h"


@implementation RTMovie

+ (NSDictionary *)attributeMappings {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
        @"magnetId" : @"id",
    }];
    [dictionary addEntriesFromDictionary:[super attributeMappings]];
    return [dictionary copy];
}

+ (NSDictionary *)listAttributeTypes {
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionaryWithDictionary:@{
        @"abridged_cast" : @"_bean:RTAbridged_cast",
    }];
    [dictionary addEntriesFromDictionary:[super listAttributeTypes]];
    return [dictionary copy];
}

@end