//
//  RTRatings.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "audience_rating" : "Upright",
  "critics_rating" : "Certified Fresh",
  "audience_score" : 67,
  "critics_score" : 89
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface RTRatings : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *audience_rating;


@property (nonatomic, assign) int audience_score;


@property (nonatomic, copy) NSString *critics_rating;


@property (nonatomic, assign) int critics_score;



@end
