//
//  RTRelease_dates.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "theater" : "2002-05-03",
  "dvd" : "2002-11-01"
}

*/

#import <Rest2Mobile/Rest2Mobile.h>


@interface RTRelease_dates : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *dvd;


@property (nonatomic, copy) NSString *theater;



@end
