//
//  RTSearchResult.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
/** Generated from json example
{
  "links" : {
    "next" : "http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=spider&page_limit=1&page=2",
    "self" : "http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=spider&page_limit=1&page=1"
  },
  "movies" : [ {
    "id" : "10122",
    "posters" : {
      "original" : "http://content7.flixster.com/movie/11/16/52/11165293_tmb.jpg",
      "detailed" : "http://content7.flixster.com/movie/11/16/52/11165293_tmb.jpg",
      "thumbnail" : "http://content7.flixster.com/movie/11/16/52/11165293_tmb.jpg",
      "profile" : "http://content7.flixster.com/movie/11/16/52/11165293_tmb.jpg"
    },
    "synopsis" : "",
    "abridged_cast" : [ {
      "name" : "Tobey Maguire",
      "id" : "162660340",
      "characters" : [ "Spider-Man/Peter Parker" ]
    }, {
      "name" : "Kirsten Dunst",
        ...

*/

#import <Rest2Mobile/Rest2Mobile.h>


@class RTLinks;

@interface RTSearchResult : MMResourceNode <NSCoding>

//field declarations

@property (nonatomic, copy) NSString *link_template;


@property (nonatomic, strong) RTLinks *links;


@property (nonatomic, copy) NSArray *movies;


@property (nonatomic, assign) int total;



@end
