//
//  RTMovieListSpec.m
//
//  File generated by Magnet rest2mobile 1.1 - Feb 4, 2015 10:17:33 AM
//  @See Also: http://developer.magnet.com
//
#import <Kiwi/Kiwi.h>
#import "RTMovieList.h"
#import "MoviesListResult.h"

#define DEFAULT_TEST_TIMEOUT 5.0

SPEC_BEGIN(RTMovieListSpec)

describe(@"RTMovieList", ^{

    RTMovieList *sut = [[RTMovieList alloc] init];


    context(@"when calling getMoviesList", ^{

        it(@"should invoke", ^{
            // FIXME: Set the expected output
            MoviesListResult *output;
            // FIXME: Set the input parameter(s)
            NSString *limit;
            NSString *country;
            NSString *apikey;

            __block MoviesListResult *_response;
            [sut getMoviesList:limit
                       country:country
                        apikey:apikey
                       success:^(MoviesListResult *response){
                          _response = response;
                       }
                       failure:^(NSError *error){
                       }];

            // Assert
            [[expectFutureValue(_response) shouldEventuallyBeforeTimingOutAfter(DEFAULT_TEST_TIMEOUT)] equal:output];
        });
    });


});

SPEC_END
