//
//  RTMoviesController.m
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
#import "RTMoviesController.h"

@implementation RTMoviesController

+ (NSDictionary *)metaData {

    NSMutableDictionary *controllerMetaData = [NSMutableDictionary dictionary];

    MMControllerMethod *method;
    //controller schema for interface RTMoviesController

    //controller schema for controller method getBoxOffice
    method = [MMControllerMethod new];
    method.name = @"getBoxOffice";
    method.path = @"api/public/v1.0/lists/movies/box_office.json";
    method.baseURL = [NSURL URLWithString:@"http://api.rottentomatoes.com"];
    method.method = @"GET";
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *rTMoviesControllerGetBoxOfficeParams = [NSMutableArray new];
    MMControllerParam *rTMoviesControllerGetBoxOfficeLimit = [MMControllerParam new];
    rTMoviesControllerGetBoxOfficeLimit.name = @"limit";
    rTMoviesControllerGetBoxOfficeLimit.style = @"QUERY";
    rTMoviesControllerGetBoxOfficeLimit.type = @"NSString *";
    rTMoviesControllerGetBoxOfficeLimit.optional = @YES;
    [rTMoviesControllerGetBoxOfficeParams addObject:rTMoviesControllerGetBoxOfficeLimit];

    MMControllerParam *rTMoviesControllerGetBoxOfficeCountry = [MMControllerParam new];
    rTMoviesControllerGetBoxOfficeCountry.name = @"country";
    rTMoviesControllerGetBoxOfficeCountry.style = @"QUERY";
    rTMoviesControllerGetBoxOfficeCountry.type = @"NSString *";
    rTMoviesControllerGetBoxOfficeCountry.optional = @YES;
    [rTMoviesControllerGetBoxOfficeParams addObject:rTMoviesControllerGetBoxOfficeCountry];

    MMControllerParam *rTMoviesControllerGetBoxOfficeApikey = [MMControllerParam new];
    rTMoviesControllerGetBoxOfficeApikey.name = @"apikey";
    rTMoviesControllerGetBoxOfficeApikey.style = @"QUERY";
    rTMoviesControllerGetBoxOfficeApikey.type = @"NSString *";
    rTMoviesControllerGetBoxOfficeApikey.optional = @YES;
    [rTMoviesControllerGetBoxOfficeParams addObject:rTMoviesControllerGetBoxOfficeApikey];

    method.parameters = [rTMoviesControllerGetBoxOfficeParams copy];
    method.returnType = @"_bean:RTBoxOfficeResult";
    [controllerMetaData setObject:method forKey:@"RTMoviesController:getBoxOffice"];

    //controller schema for controller method getTopRentals
    method = [MMControllerMethod new];
    method.name = @"getTopRentals";
    method.path = @"api/public/v1.0/lists/dvds/top_rentals.json";
    method.baseURL = [NSURL URLWithString:@"http://api.rottentomatoes.com"];
    method.method = @"GET";
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *rTMoviesControllerGetTopRentalsParams = [NSMutableArray new];
    MMControllerParam *rTMoviesControllerGetTopRentalsLimit = [MMControllerParam new];
    rTMoviesControllerGetTopRentalsLimit.name = @"limit";
    rTMoviesControllerGetTopRentalsLimit.style = @"QUERY";
    rTMoviesControllerGetTopRentalsLimit.type = @"NSString *";
    rTMoviesControllerGetTopRentalsLimit.optional = @YES;
    [rTMoviesControllerGetTopRentalsParams addObject:rTMoviesControllerGetTopRentalsLimit];

    MMControllerParam *rTMoviesControllerGetTopRentalsCountry = [MMControllerParam new];
    rTMoviesControllerGetTopRentalsCountry.name = @"country";
    rTMoviesControllerGetTopRentalsCountry.style = @"QUERY";
    rTMoviesControllerGetTopRentalsCountry.type = @"NSString *";
    rTMoviesControllerGetTopRentalsCountry.optional = @YES;
    [rTMoviesControllerGetTopRentalsParams addObject:rTMoviesControllerGetTopRentalsCountry];

    MMControllerParam *rTMoviesControllerGetTopRentalsApikey = [MMControllerParam new];
    rTMoviesControllerGetTopRentalsApikey.name = @"apikey";
    rTMoviesControllerGetTopRentalsApikey.style = @"QUERY";
    rTMoviesControllerGetTopRentalsApikey.type = @"NSString *";
    rTMoviesControllerGetTopRentalsApikey.optional = @YES;
    [rTMoviesControllerGetTopRentalsParams addObject:rTMoviesControllerGetTopRentalsApikey];

    method.parameters = [rTMoviesControllerGetTopRentalsParams copy];
    method.returnType = @"_bean:RTTopRentalsResult";
    [controllerMetaData setObject:method forKey:@"RTMoviesController:getTopRentals"];

    //controller schema for controller method search
    method = [MMControllerMethod new];
    method.name = @"search";
    method.path = @"api/public/v1.0/movies.json";
    method.baseURL = [NSURL URLWithString:@"http://api.rottentomatoes.com"];
    method.method = @"GET";
    method.produces = [NSSet setWithObjects:@"application/json", nil];

    NSMutableArray *rTMoviesControllerSearchParams = [NSMutableArray new];
    MMControllerParam *rTMoviesControllerSearchQ = [MMControllerParam new];
    rTMoviesControllerSearchQ.name = @"q";
    rTMoviesControllerSearchQ.style = @"QUERY";
    rTMoviesControllerSearchQ.type = @"NSString *";
    rTMoviesControllerSearchQ.optional = @YES;
    [rTMoviesControllerSearchParams addObject:rTMoviesControllerSearchQ];

    MMControllerParam *rTMoviesControllerSearchPage_limit = [MMControllerParam new];
    rTMoviesControllerSearchPage_limit.name = @"page_limit";
    rTMoviesControllerSearchPage_limit.style = @"QUERY";
    rTMoviesControllerSearchPage_limit.type = @"NSString *";
    rTMoviesControllerSearchPage_limit.optional = @YES;
    [rTMoviesControllerSearchParams addObject:rTMoviesControllerSearchPage_limit];

    MMControllerParam *rTMoviesControllerSearchPage = [MMControllerParam new];
    rTMoviesControllerSearchPage.name = @"page";
    rTMoviesControllerSearchPage.style = @"QUERY";
    rTMoviesControllerSearchPage.type = @"NSString *";
    rTMoviesControllerSearchPage.optional = @YES;
    [rTMoviesControllerSearchParams addObject:rTMoviesControllerSearchPage];

    MMControllerParam *rTMoviesControllerSearchApikey = [MMControllerParam new];
    rTMoviesControllerSearchApikey.name = @"apikey";
    rTMoviesControllerSearchApikey.style = @"QUERY";
    rTMoviesControllerSearchApikey.type = @"NSString *";
    rTMoviesControllerSearchApikey.optional = @YES;
    [rTMoviesControllerSearchParams addObject:rTMoviesControllerSearchApikey];

    method.parameters = [rTMoviesControllerSearchParams copy];
    method.returnType = @"_bean:RTSearchResult";
    [controllerMetaData setObject:method forKey:@"RTMoviesController:search"];


    return [controllerMetaData copy];
}

@end
