//
//  RTMoviesController.h
//
//  File generated by Magnet rest2mobile 1.1 - Feb 7, 2015 11:25:59 AM
//  @See Also: http://developer.magnet.com
//
#import <Rest2Mobile/Rest2Mobile.h>
@class RTBoxOfficeResult;
@class RTSearchResult;
@class RTTopRentalsResult;

@protocol RTMoviesControllerProtocol <NSObject>

@optional

/**
 Generated from URL GET http://api.rottentomatoes.com/api/public/v1.0/lists/movies/box_office.json?limit=10&country=us&apikey=wrtc95qtd7c84rvmdv23tggg
 GET api/public/v1.0/lists/movies/box_office.json
 @param limit style:QUERY
 @param country style:QUERY
 @param apikey style:QUERY
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getBoxOffice:(NSString *)limit
                 country:(NSString *)country
                  apikey:(NSString *)apikey
                 success:(void (^)(RTBoxOfficeResult *response))success
                 failure:(void (^)(NSError *error))failure;

/**
 Generated from URL GET http://api.rottentomatoes.com/api/public/v1.0/lists/dvds/top_rentals.json?limit=10&country=us&apikey=wrtc95qtd7c84rvmdv23tggg
 GET api/public/v1.0/lists/dvds/top_rentals.json
 @param limit style:QUERY
 @param country style:QUERY
 @param apikey style:QUERY
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)getTopRentals:(NSString *)limit
                  country:(NSString *)country
                   apikey:(NSString *)apikey
                  success:(void (^)(RTTopRentalsResult *response))success
                  failure:(void (^)(NSError *error))failure;

/**
 Generated from URL GET http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=spider&page_limit=1&page=1&apikey=wrtc95qtd7c84rvmdv23tggg
 GET api/public/v1.0/movies.json
 @param q style:QUERY
 @param page_limit style:QUERY
 @param page style:QUERY
 @param apikey style:QUERY
 @param success The block to be executed on the completion of a successful request. This block has no return value and takes one argument: the object/primitive constructed from the response data of the request.
 @param failure The block to be executed on the completion of an unsuccessful request. This block has no return value and takes one argument: the error that occurred during the request.
 @return A 'MMCall' object.
 */
- (MMCall *)search:(NSString *)q
        page_limit:(NSString *)page_limit
              page:(NSString *)page
            apikey:(NSString *)apikey
           success:(void (^)(RTSearchResult *response))success
           failure:(void (^)(NSError *error))failure;

@end

@interface RTMoviesController : MMController<RTMoviesControllerProtocol>

@end
